"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0(33_5$$mtoe*8a6jz)gohoud=l96^r$jifldi78^(19vs17=%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # set to False in production to avoid exposing debug info

ALLOWED_HOSTS = []


# Application definition

# After login, redirect users to a page that exists
LOGIN_REDIRECT_URL = '/books/'   # or any page you want users to land on


AUTH_USER_MODEL = 'bookshelf.CustomUser'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LibraryProject.bookshelf',
    'LibraryProject.relationship_app.apps.RelationshipAppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

# Only allow scripts and styles from our own domain
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")


ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# security headers
SECURE_BROWSER_XSS_FILTER = True #Enable browser XSS filter
SECURE_CONTENT_TYPE_NOSNIFF = True #Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY' #Prevent clickjacking by disallowing iframing

# secure cookies
CSRF_COOKIE_SECURE = True # ensure CSRF cookie is only sent over HTTPS only
SESSION_COOKIE_SECURE = True # ensure session cookie is only sent over HTTPS only


# redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True #ensures all traffic uses HTTPS, protecting data in transit

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
# Explanation: Tells browsers to only connect to this site using HTTPS for the next year

SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Explanation: Apply HSTS policy to all subdomains, not just main domain

SECURE_HSTS_PRELOAD = True
# Explanation: Allows your site to be included in browser preload lists for HSTS

# Secure Cookies
SESSION_COOKIE_SECURE = True
# Explanation: Only send session cookies over HTTPS

CSRF_COOKIE_SECURE = True
# Explanation: Only send CSRF cookies over HTTPS

# Additional HTTP Security Headers
X_FRAME_OPTIONS = 'DENY'
# Explanation: Prevents your site from being embedded in iframes, protecting against clickjacking

SECURE_CONTENT_TYPE_NOSNIFF = True
# Explanation: Prevents browsers from MIME-sniffing content types (avoids content-type attacks)

SECURE_BROWSER_XSS_FILTER = True
# Explanation: Enables the browser's built-in XSS filter to block some types of XSS attacks